spring:
  security:
    user:
      name: "chen"
      password: "chen"
  application:
    name: admin-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  boot:
    admin:
      discovery:
        enabled: false
server:
  port: 7777
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS